### ISSUE TITLE
web3-function build error

### ISSUE THREAD

**Issue by rout-horizon** [gelatodigital/web3-functions-template#29]
Doing a fresh clone of the repo and filling the .env file. I'm getting this error while running the command `npx w3f test web3-functions/oracle/index.ts --logs --chain-id 421614 --debug`

**My .env file**
```
ALCHEMY_ID=https://sy-sxxxxxxx-aura.arbitrum-sepolia.quiknode.pro/80exxxxxxxxxxxxxxxxxxxxxxxd98xx2/
PROVIDER_URLS=https://sy-sxxxxxxx-aura.arbitrum-sepolia.quiknode.pro/80xxxxxxxxxxxxxxxxxxxxxxxd98xx2/

```

**Error**
```
Web3Function onRun result:
 ✗ Error: Proxy provider cannot be instantiated, default chainId 5 doesn't have a provider configured
```
 
 And after updating the sdk packages to latest versions I'm getting the same error as before slightly different.
```
 "@gelatonetwork/automate-sdk": "^3.0.10",
 "@gelatonetwork/web3-functions-sdk": "^2.4.1",
```

```
Web3Function onRun result:
 ✗ Error: Proxy provider cannot be instantiated, default chainId 11155111 doesn't have a provider configured
```

**Comment by goums** [comment]
from your .env, it looks like your alchemy id is not set properly:
```
ALCHEMY_ID=https://sy-sxxxxxxx-aura.arbitrum-sepolia.quiknode.pro/80exxxxxxxxxxxxxxxxxxxxxxxd98xx2/
```

it should be just the alchemy key part (random looking string)

**Comment by rout-horizon** [comment]
@goums Definitely I won't put the real rpc url in public github, the idea was to show that I'm using quicknode rpc. Are you saying it works only with alchemy ?

**Comment by goums** [comment]
Actually no, you should not need alchemy on this repo.

Could you try adding sepolia provider in your `PROVIDER_URLS` env?
You can have multiple providers, separated by comma value,
eg:
```
PROVIDER_URLS=https://rpc.ankr.com/eth_sepolia,xxxx
```

**Comment by goums** [comment]
Oh actually I think the issue is on your command line:
```
npx w3f test web3-functions/oracle/index.ts --logs --chain-id 421614 --debug
```

it should be `--chain-id=421614` not `--chain-id 421614`: 
```
npx w3f test web3-functions/oracle/index.ts --logs --chain-id=421614 --debug
```
